[package]
name = "mediacontrol"
version = "0.1.0"
edition = "2021"

[lib]
# crate-type = ["cdylib"]
crate-type = ["staticlib"]

[dependencies]
windows = {version = "0.54.0", features = [
  "Media",
  "Media_Control",
  "implement",
  "Win32_Foundation",
  "Win32_System_Com",
  "Win32_System_Variant",
  "Win32_System"
  ]}
windows-interface = "0.53.0"

# [build-dependencies]
# windows-bindgen = "0.55.0"
# windows-metadata = "0.55.0"
