[package]
name = "mediacontrol"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
env_logger = "0.11.3"
futures = "0.3.31"
log = "0.4.21"
mpris-server = "0.8.1"
tokio = { version = "1", features = ["rt", "net", "sync"] }
tracing-log = "0.2.0"
tracing-subscriber = "0.3.19"
windows = {version = "0.54.0", features = [
  "implement",
  "Foundation_Collections",
  "Media",
  "Media_Control",
  "Storage_Streams",
  "Win32_Foundation",
  "Win32_System_WinRT",
  "Win32_UI_WindowsAndMessaging"
]}
windows-core = "0.54.0"
windows-interface = "0.53.0"
wine-macro = "*"
zbus = { version = "*", default-features = false, features = ["async-io", "wine"] }
[patch.crates-io]
zbus = { path = "zbus/zbus" }
mpris-server = { git = "https://github.com/SeaDve/mpris-server.git", rev = "d840761a4405fa344f5b46f1065f2d450af049f9" }

[profile.release]
opt-level = "z"
